version: 2

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 2ff9b9aeed7f53a2dd24cfe91387c2a9b1c8d8aada3c49c2569dced44e03918f
    docker:
    - image: circleci/php:7.1-cli-node-browsers
    steps:
    - checkout
    - run:
        name: Setup php dependencies
        command: |
          sudo apt install -y libbz2-dev
          sudo docker-php-ext-install bz2
    - run:
        name: Setup project dependencies
        command: |
          sudo composer self-update
    - run:
        name: Setup Code Climate test-reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
    - run: sudo composer self-update
    - restore_cache
      keys:
      - composer-v1-{{ checksum "composer.json" }}
      - compsoer-v1-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: composer-v1-{{ checksum "composer.json" }}
        paths:
        - vendor
    - run:
        name: Run tests
        command: |
          sudo docker-php-ext-enable xdebug
          ./cc-test-reporter before-build
          sudo vendor/bin/phpunit --coverage-clover clover.xml
          ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
